[package]
name = "rabbitinspect"
version = "0.2.0"
edition = "2021"

[lib]
name = "rabbitinspect"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module"] }
rustpython-parser = "0.4.0"
rustpython-ast = "0.4.0"
rustc-hash = "2.1"

[profile.release]
opt-level = 3
lto = true
strip = true
