# ruff: noqa: I001
from typing import Any

def analyze_code(source: str) -> list[dict[str, Any]]: ...
def apply_fixes(source: str, fixes: list[dict[str, Any]]) -> str: ...
def perf_start(interval_ms: float = ..., max_depth: int = ...) -> None: ...
def perf_stop() -> dict[str, Any]: ...
def perf_running() -> bool: ...
def perf_now_ms() -> float: ...
def perf_record_span(method: str, route: str, status: int, start_ms: float, end_ms: float) -> None: ...
def perf_reset() -> None: ...
def perf_record_query(sql: str, duration_ms: float) -> None: ...
